// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnet_epl.Data;

#nullable disable

namespace dotnet_epl.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("dotnet_epl.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AttackValue")
                        .HasColumnType("int");

                    b.Property<int>("DefenceValue")
                        .HasColumnType("int");

                    b.Property<int>("Draws")
                        .HasColumnType("int");

                    b.Property<int>("Losses")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AttackValue = 4,
                            DefenceValue = 3,
                            Draws = 0,
                            Losses = 0,
                            Name = "Arsenal",
                            Points = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 2,
                            AttackValue = 1,
                            DefenceValue = 2,
                            Draws = 0,
                            Losses = 0,
                            Name = "Aston Villa",
                            Points = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 3,
                            AttackValue = 2,
                            DefenceValue = 1,
                            Draws = 0,
                            Losses = 0,
                            Name = "Bournemouth",
                            Points = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 4,
                            AttackValue = 2,
                            DefenceValue = 1,
                            Draws = 0,
                            Losses = 0,
                            Name = "Brentford",
                            Points = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 5,
                            AttackValue = 1,
                            DefenceValue = 3,
                            Draws = 0,
                            Losses = 0,
                            Name = "Brighton",
                            Points = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 6,
                            AttackValue = 4,
                            DefenceValue = 5,
                            Draws = 0,
                            Losses = 0,
                            Name = "Chelsea",
                            Points = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 7,
                            AttackValue = 3,
                            DefenceValue = 2,
                            Draws = 0,
                            Losses = 0,
                            Name = "Crystal Palace",
                            Points = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 8,
                            AttackValue = 4,
                            DefenceValue = 2,
                            Draws = 0,
                            Losses = 0,
                            Name = "Everton",
                            Points = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 9,
                            AttackValue = 2,
                            DefenceValue = 1,
                            Draws = 0,
                            Losses = 0,
                            Name = "Fulham",
                            Points = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 10,
                            AttackValue = 3,
                            DefenceValue = 2,
                            Draws = 0,
                            Losses = 0,
                            Name = "Leeds",
                            Points = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 11,
                            AttackValue = 2,
                            DefenceValue = 3,
                            Draws = 0,
                            Losses = 0,
                            Name = "Leicester",
                            Points = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 12,
                            AttackValue = 5,
                            DefenceValue = 4,
                            Draws = 0,
                            Losses = 0,
                            Name = "Liverpool",
                            Points = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 13,
                            AttackValue = 4,
                            DefenceValue = 5,
                            Draws = 0,
                            Losses = 0,
                            Name = "Man City",
                            Points = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 14,
                            AttackValue = 5,
                            DefenceValue = 3,
                            Draws = 0,
                            Losses = 0,
                            Name = "Man United",
                            Points = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 15,
                            AttackValue = 3,
                            DefenceValue = 2,
                            Draws = 0,
                            Losses = 0,
                            Name = "Newcastle",
                            Points = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 16,
                            AttackValue = 2,
                            DefenceValue = 1,
                            Draws = 0,
                            Losses = 0,
                            Name = "Nottingham",
                            Points = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 17,
                            AttackValue = 1,
                            DefenceValue = 2,
                            Draws = 0,
                            Losses = 0,
                            Name = "Southampton",
                            Points = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 18,
                            AttackValue = 5,
                            DefenceValue = 4,
                            Draws = 0,
                            Losses = 0,
                            Name = "Tottenham",
                            Points = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 19,
                            AttackValue = 3,
                            DefenceValue = 1,
                            Draws = 0,
                            Losses = 0,
                            Name = "West Ham",
                            Points = 0,
                            Wins = 0
                        },
                        new
                        {
                            Id = 20,
                            AttackValue = 4,
                            DefenceValue = 1,
                            Draws = 0,
                            Losses = 0,
                            Name = "Wolves",
                            Points = 0,
                            Wins = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
